spring:
  datasource:
    url: "jdbc:h2:mem:devTest"
    driver-class-name: "org.h2.Driver"
    username: "admin"
    password: "adminpassword"
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
