spring:
  banner:
    location: logo.txt
    charset: UTF-8
  profiles:
    active: application-dev
  datasource:
    url: "jdbc:h2:mem:devTest"
    driver-class-name: "org.h2.Driver"
    username: "admin"
    password: "password"
  h2:
      console:
        enabled: true
        path: /console